// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBb00eGFnA0OeHTENRXa3Jauk73-SljW3g',
    appId: '1:12168987667:web:ac0e0f8a78c53895fc2be6',
    messagingSenderId: '12168987667',
    projectId: 'fitness-tracker-84e74',
    authDomain: 'fitness-tracker-84e74.firebaseapp.com',
    storageBucket: 'fitness-tracker-84e74.appspot.com',
    measurementId: 'G-9FMYT3QCVS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0Fp2H0lK5Am9N-WEMtu0QhSF1Lyb4hMs',
    appId: '1:12168987667:android:14e28bd8d9e829aafc2be6',
    messagingSenderId: '12168987667',
    projectId: 'fitness-tracker-84e74',
    storageBucket: 'fitness-tracker-84e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCH8TyrdlOdqbu55c5sEV6tuv9M2uUFQs',
    appId: '1:12168987667:ios:b5a8b7787f7ee7e2fc2be6',
    messagingSenderId: '12168987667',
    projectId: 'fitness-tracker-84e74',
    storageBucket: 'fitness-tracker-84e74.appspot.com',
    iosBundleId: 'com.example.workouttracking3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCH8TyrdlOdqbu55c5sEV6tuv9M2uUFQs',
    appId: '1:12168987667:ios:b5a8b7787f7ee7e2fc2be6',
    messagingSenderId: '12168987667',
    projectId: 'fitness-tracker-84e74',
    storageBucket: 'fitness-tracker-84e74.appspot.com',
    iosBundleId: 'com.example.workouttracking3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBb00eGFnA0OeHTENRXa3Jauk73-SljW3g',
    appId: '1:12168987667:web:3a9f6d1e2c447611fc2be6',
    messagingSenderId: '12168987667',
    projectId: 'fitness-tracker-84e74',
    authDomain: 'fitness-tracker-84e74.firebaseapp.com',
    storageBucket: 'fitness-tracker-84e74.appspot.com',
    measurementId: 'G-LDX25WF53C',
  );
}
